# Generated by Django 3.2.8 on 2021-11-01 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_exame', models.CharField(max_length=200)),
                ('preparo_para_exame', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_para_realizacao_exame', models.IntegerField()),
                ('valor_exame', models.CharField(max_length=100)),
                ('date_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_exame', models.ImageField(blank=True, upload_to='fotos/%d/%m/%y/')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
    ]
