# Generated by Django 3.2.8 on 2021-11-23 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_exame', models.CharField(max_length=200)),
                ('preparo_para_exame', models.TextField()),
                ('sobre_o_exame', models.TextField()),
                ('tempo_para_realizacao_exame', models.IntegerField()),
                ('valor_exame', models.CharField(max_length=100)),
                ('date_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_exame', models.ImageField(blank=True, upload_to='fotos/%d/%m/%y/')),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_da_requisicao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('medico_requerente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exames.medico')),
                ('nome_do_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exames.exame')),
                ('nome_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_do_resultado', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('laudo_exame', models.TextField(blank=True, null=True)),
                ('arquivo_exame', models.ImageField(blank=True, upload_to='fotos/%d/%m/%y/')),
                ('publicada', models.BooleanField(default=False)),
                ('tipo_exame', models.CharField(choices=[('glicose', 'Glicose'), ('colesterol', 'Colesterol'), ('teste covid', 'Teste Covid'), ('testetoxicologico', 'Teste toxicológico')], default='glicose', max_length=100)),
                ('medico_requerente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exames.medico')),
                ('nome_do_exame', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exames.exame')),
                ('nome_paciente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exames.requisicaoexame')),
            ],
        ),
    ]
