# Generated by Django 3.2.8 on 2021-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_auto_20211126_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='valor_exame',
        ),
        migrations.AddField(
            model_name='exame',
            name='tipo_exame',
            field=models.CharField(choices=[('glicose', 'glicose'), ('colesterol', 'colesterol'), ('testecovid', 'teste Covid'), ('testetoxicologico', 'teste toxicológico')], default='glicose', max_length=100),
        ),
        migrations.AlterField(
            model_name='exame',
            name='preparo_para_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='sobre_o_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='tempo_para_realizacao_exame',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='resultado_teste_covid',
            field=models.CharField(choices=[('positivo', 'positivo'), ('negativo', 'negativo'), ('NSA', 'NSA')], default='NSA', max_length=100),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='resultado_teste_toxicológico',
            field=models.CharField(choices=[('positivo', 'positivo'), ('negativo', 'negativo'), ('NSA', 'NSA')], default='NSA', max_length=100),
        ),
        migrations.AlterField(
            model_name='resultadoexame',
            name='tipo_exame',
            field=models.CharField(choices=[('glicose', 'glicose'), ('colesterol', 'colesterol'), ('testecovid', 'teste Covid'), ('testetoxicologico', 'teste toxicológico')], default='glicose', max_length=100),
        ),
    ]
