# Generated by Django 3.2.8 on 2021-11-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_rename_receita_exame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='modo_preparo',
            new_name='sobre_o_exame',
        ),
    ]
