# Generated by Django 3.2.8 on 2021-11-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_resultadoexame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoexame',
            old_name='médico_requerente',
            new_name='medico_requerente',
        ),
    ]
