# Generated by Django 3.2.8 on 2021-11-07 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exames', '0005_rename_médico_requerente_resultadoexame_medico_requerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_da_requisicao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nome_do_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exames.exame')),
                ('nome_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
