# Generated by Django 3.2.8 on 2021-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0007_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaoexame',
            name='medico_requerente',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
