# Generated by Django 3.2.8 on 2021-11-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0008_requisicaoexame_medico_requerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaoexame',
            name='medico_requerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exames.medico'),
        ),
    ]
