# Generated by Django 3.2.8 on 2021-11-15 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0009_alter_requisicaoexame_medico_requerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoexame',
            name='requisicao',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='exames.requisicaoexame'),
        ),
    ]
