# Generated by Django 3.2.8 on 2021-11-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0011_alter_resultadoexame_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexame',
            name='requisicao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exames.requisicaoexame'),
        ),
    ]
