# Generated by Django 3.2.8 on 2021-11-15 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0013_remove_resultadoexame_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexame',
            name='nome_do_exame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exames.exame'),
        ),
    ]
