# Generated by Django 3.2.8 on 2021-11-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211107_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipousuario',
        ),
    ]
